# Generated by Django 6.1.1 on 2026-10-02 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_path', models.CharField(help_text='storage key of the original PDF', max_length=500)),
                ('source_filename', models.CharField(max_length=255)),
                ('mineru_markdown', models.TextField(blank=True, default='')),
                ('mineru_batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('parse_status', models.CharField(choices=[('uploaded', '已上传'), ('parsing', '解析中'), ('parsed', '已解析'), ('failed', '解析失败')], default='uploaded', max_length=20)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('structured_json', models.JSONField()),
                ('change_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('resume', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resumeversion'),
        ),
    ]
