# Generated by Django 6.1.1 on 2026-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='mineru_source_hash',
            field=models.CharField(blank=True, default='', help_text='md5 of the PDF bytes parsed into mineru_markdown — PDF unchanged means never re-parse (cache key)', max_length=64),
        ),
    ]
