# Generated by Django 6.1.1 on 2026-10-03 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_jobtarget_jobselfcheck'),
        ('resumes', '0002_resume_mineru_source_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('created', 'created'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='created', max_length=20)),
                ('current_stage', models.CharField(choices=[('quiz', 'quiz'), ('coding', 'coding'), ('interview', 'interview'), ('summary', 'summary')], default='interview', max_length=20)),
                ('settings_json', models.JSONField(default=dict, help_text='{"strict_mode": false, "duration_min": 30}')),
                ('interview_state_json', models.JSONField(default=dict, help_text='{"phase", "time_used_min", "asked_question_ids", "evals_digest", "dangling_threads", "found_flaws", "found_highlights", "plan_adjustments"}')),
                ('context_summary', models.TextField(blank=True, default='')),
                ('context_summary_turn_seq', models.IntegerField(default=0)),
                ('last_turn_seq', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_sessions', to='jobs.jobposition')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_sessions', to='jobs.jobprofile')),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_sessions', to='resumes.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_json', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='sparr_sessions.applicationsession')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('interviewer', 'interviewer'), ('candidate', 'candidate'), ('system', 'system')], max_length=12)),
                ('content', models.TextField()),
                ('eval_json', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict, help_text='{"phase", "question_id", "depth", "interrupted", "partial", "plan_adjustment"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='sparr_sessions.applicationsession')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('application', 'seq')},
            },
        ),
    ]
