# Generated by Django 6.1.1 on 2026-10-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparr_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsession',
            name='review_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
