# Generated by Django 6.1.1 on 2026-10-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparr_sessions', '0002_applicationsession_review_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('qtype', models.CharField(choices=[('single', 'single'), ('multi', 'multi'), ('short_answer', 'short_answer')], max_length=16)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('stem', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('reference_answer', models.JSONField(default=list)),
                ('scoring_points', models.JSONField(default=list)),
                ('knowledge_tag', models.CharField(blank=True, default='', max_length=100)),
                ('score_full', models.PositiveSmallIntegerField(default=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='sparr_sessions.applicationsession')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('application', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0)),
                ('judge_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sparr_sessions.examquestion')),
            ],
            options={
                'ordering': ['question__seq'],
            },
        ),
    ]
