# Generated by Django 6.1.1 on 2026-10-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparr_sessions', '0003_examquestion_examanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('stem', models.TextField()),
                ('function_signature', models.TextField(blank=True, default='')),
                ('examples', models.JSONField(default=list)),
                ('constraints', models.TextField(blank=True, default='')),
                ('language_hint', models.CharField(blank=True, default='python', max_length=20)),
                ('score_full', models.PositiveSmallIntegerField(default=50)),
                ('reference_solution', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='sparr_sessions.applicationsession')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('application', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='CodingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('judge_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sparr_sessions.codingquestion')),
            ],
            options={
                'ordering': ['question__seq'],
            },
        ),
    ]
