"""Seed the shared job catalog (PLAN.md §5.2) — idempotent upsert by (category, title, level)."""
from django.core.management.base import BaseCommand

from apps.jobs.models import JobPosition

# skill names are canonical taxonomy keys (see apps/profiling/taxonomy.py)
JOBS = [
    # ================= 后端 =================
    {
        "category": "后端", "title": "后端开发工程师", "level": "校招",
        "description": "负责服务端核心链路开发，保障高可用与性能。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": False},
            {"skill": "java", "weight": 5, "required": False},
            {"skill": "golang", "weight": 3, "required": False},
            {"skill": "计算机网络", "weight": 5, "required": True},
            {"skill": "操作系统", "weight": 4, "required": True},
            {"skill": "mysql", "weight": 5, "required": True},
            {"skill": "redis", "weight": 4, "required": False},
            {"skill": "消息队列", "weight": 3, "required": False},
            {"skill": "linux", "weight": 3, "required": False},
            {"skill": "git", "weight": 2, "required": False},
        ],
        "affinity_tags": ["高并发", "分布式", "微服务", "用户中心", "订单系统", "API 设计"],
        "knowledge_points": ["TCP/HTTP 协议", "进程/线程/内存", "MySQL 索引与事务", "锁与并发",
                             "Redis 缓存与一致性", "消息队列", "分布式基础", "RESTful 设计"],
        "coding_topics": ["线程安全数据结构", "SQL 场景题", "接口幂等设计", "缓存穿透/雪崩方案"],
        "interview_focus": ["基础八股", "项目深挖", "场景设计", "追问数据指标"],
    },
    {
        "category": "后端", "title": "后端开发工程师", "level": "社招",
        "description": "主导复杂系统设计与演进，解决高并发高可用难题。",
        "skill_requirements": [
            {"skill": "java", "weight": 5, "required": False},
            {"skill": "golang", "weight": 4, "required": False},
            {"skill": "python", "weight": 4, "required": False},
            {"skill": "分布式", "weight": 5, "required": True},
            {"skill": "高并发", "weight": 5, "required": True},
            {"skill": "mysql", "weight": 5, "required": True},
            {"skill": "redis", "weight": 5, "required": True},
            {"skill": "消息队列", "weight": 4, "required": False},
            {"skill": "kubernetes", "weight": 3, "required": False},
            {"skill": "spring", "weight": 3, "required": False},
        ],
        "affinity_tags": ["高并发", "分布式", "微服务", "订单系统", "性能优化", "架构设计"],
        "knowledge_points": ["分布式事务与一致性", "分库分表", "高可用架构", "性能调优",
                             "缓存体系设计", "消息可靠投递", "容量规划"],
        "coding_topics": ["限流器实现", "分布式 ID 生成", "热点账户设计", "延迟队列设计"],
        "interview_focus": ["系统设计", "架构决策复盘", "故障处理经历", "技术视野"],
    },
    {
        "category": "后端", "title": "后端开发实习生", "level": "实习",
        "description": "参与服务端功能开发，配合完成接口与数据层工作。",
        "skill_requirements": [
            {"skill": "python", "weight": 4, "required": False},
            {"skill": "java", "weight": 4, "required": False},
            {"skill": "计算机网络", "weight": 4, "required": True},
            {"skill": "mysql", "weight": 4, "required": True},
            {"skill": "linux", "weight": 2, "required": False},
            {"skill": "git", "weight": 2, "required": False},
            {"skill": "django", "weight": 3, "required": False},
            {"skill": "spring", "weight": 3, "required": False},
        ],
        "affinity_tags": ["API 设计", "CRUD", "用户中心", "数据管道"],
        "knowledge_points": ["HTTP 基础", "SQL 基础", "一门后端框架", "Git 协作"],
        "coding_topics": ["简单 SQL", "接口设计", "字符串/数组题"],
        "interview_focus": ["基础扎实度", "学习能力", "项目真实性"],
    },
    # ================= 前端 =================
    {
        "category": "前端", "title": "前端开发工程师", "level": "校招",
        "description": "负责 Web/移动端界面开发与交互体验优化。",
        "skill_requirements": [
            {"skill": "javascript", "weight": 5, "required": True},
            {"skill": "typescript", "weight": 4, "required": False},
            {"skill": "react", "weight": 5, "required": False},
            {"skill": "vue", "weight": 5, "required": False},
            {"skill": "css", "weight": 4, "required": True},
            {"skill": "浏览器原理", "weight": 4, "required": True},
            {"skill": "工程化", "weight": 3, "required": False},
            {"skill": "git", "weight": 2, "required": False},
        ],
        "affinity_tags": ["组件库", "可视化", "小程序", "H5", "交互体验", "性能优化"],
        "knowledge_points": ["JS 事件循环与作用域", "CSS 布局与响应式", "浏览器渲染原理",
                             "框架状态管理", "前端性能优化", "工程化与构建"],
        "coding_topics": ["手写防抖/节流", "手写 Promise/深拷贝", "组件封装题", "布局实现题"],
        "interview_focus": ["JS 基础", "框架原理", "项目深挖（交互/性能）", "工程化实践"],
    },
    {
        "category": "前端", "title": "前端开发工程师", "level": "社招",
        "description": "主导前端架构与体验建设，解决复杂交互与性能问题。",
        "skill_requirements": [
            {"skill": "javascript", "weight": 5, "required": True},
            {"skill": "typescript", "weight": 5, "required": True},
            {"skill": "react", "weight": 5, "required": False},
            {"skill": "vue", "weight": 5, "required": False},
            {"skill": "工程化", "weight": 5, "required": True},
            {"skill": "浏览器原理", "weight": 4, "required": True},
            {"skill": "css", "weight": 4, "required": False},
        ],
        "affinity_tags": ["组件库", "可视化", "性能优化", "架构设计", "交互体验"],
        "knowledge_points": ["框架源码级理解", "渲染性能", "微前端", "构建优化", "监控与稳定性"],
        "coding_topics": ["虚拟列表实现", "框架状态管理设计", "首屏优化方案", "错误边界设计"],
        "interview_focus": ["架构能力", "性能攻坚经历", "工程化体系", "带人/推动经历"],
    },
    # ================= 算法 =================
    {
        "category": "算法", "title": "算法工程师（机器学习/深度学习）", "level": "校招",
        "description": "负责模型研发与落地，覆盖 CV/NLP/多模态等方向。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "机器学习", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "c++", "weight": 2, "required": False},
            {"skill": "nlp", "weight": 3, "required": False},
            {"skill": "cv", "weight": 3, "required": False},
            {"skill": "强化学习", "weight": 3, "required": False},
        ],
        "affinity_tags": ["大模型", "视觉感知", "推荐系统", "医学图像", "机器人", "论文/竞赛"],
        "knowledge_points": ["深度学习基础（CNN/RNN/Transformer）", "训练调参与正则化",
                             "损失函数与评估指标", "经典模型对比", "数据处理与增强", "数学基础"],
        "coding_topics": ["手写注意力机制", "数据加载与预处理", "模型训练脚本", "指标实现"],
        "interview_focus": ["论文/项目深挖", "模型选型理由", "实验设计", "复现能力"],
    },
    {
        "category": "算法", "title": "算法工程师（大模型/多模态）", "level": "社招",
        "description": "负责大模型训练/推理/应用落地，解决实际业务问题。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "transformer", "weight": 5, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "分布式", "weight": 3, "required": False},
            {"skill": "强化学习", "weight": 3, "required": False},
        ],
        "affinity_tags": ["大模型", "多模态", "视觉感知", "机器人", "论文/竞赛", "落地应用"],
        "knowledge_points": ["Transformer 全家桶", "预训练/微调/对齐", "推理加速与量化",
                             "RAG 与应用架构", "评测体系", "分布式训练"],
        "coding_topics": ["手写 KV Cache", "推理服务设计", "数据管道实现", "训练超参排查"],
        "interview_focus": ["大模型项目深挖", "落地效果与指标", "技术判断力", "论文/专利"],
    },
    # ================= 产品 =================
    {
        "category": "产品", "title": "产品经理", "level": "校招",
        "description": "负责需求洞察与产品设计，推动产品迭代落地。",
        "skill_requirements": [
            {"skill": "需求分析", "weight": 5, "required": True},
            {"skill": "产品设计", "weight": 5, "required": True},
            {"skill": "数据分析", "weight": 4, "required": True},
            {"skill": "竞品分析", "weight": 4, "required": False},
            {"skill": "用户研究", "weight": 3, "required": False},
            {"skill": "文档能力", "weight": 4, "required": False},
        ],
        "affinity_tags": ["需求文档", "用户研究", "增长", "产品设计", "数据分析", "项目推动"],
        "knowledge_points": ["需求分析方法", "产品设计流程", "数据指标体系", "竞品分析框架",
                             "用户体验原则", "项目推动与协作"],
        "coding_topics": ["需求拆解题（给场景出方案）", "指标设计题", "优先级排序题"],
        "interview_focus": ["产品 sense", "需求案例深挖", "数据驱动", "沟通与推动"],
    },
    {
        "category": "产品", "title": "高级产品经理", "level": "社招",
        "description": "主导产品线规划与增长，对业务结果负责。",
        "skill_requirements": [
            {"skill": "需求分析", "weight": 5, "required": True},
            {"skill": "产品设计", "weight": 5, "required": True},
            {"skill": "数据分析", "weight": 5, "required": True},
            {"skill": "用户研究", "weight": 4, "required": True},
            {"skill": "竞品分析", "weight": 4, "required": False},
        ],
        "affinity_tags": ["增长", "商业化", "项目推动", "数据分析", "产品设计"],
        "knowledge_points": ["产品战略与路线图", "增长模型", "商业化设计", "组织协作", "风险控制"],
        "coding_topics": ["从 0 到 1 方案题", "增长实验设计", "数据归因题"],
        "interview_focus": ["业务结果复盘", "决策过程", "带团队/跨部门推动", "行业洞察"],
    },
    # ================= 数据 =================
    {
        "category": "数据", "title": "数据开发工程师", "level": "校招",
        "description": "负责数据仓库与数据管道建设，支撑业务分析。",
        "skill_requirements": [
            {"skill": "sql", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "数仓", "weight": 4, "required": True},
            {"skill": "etl", "weight": 3, "required": False},
            {"skill": "spark", "weight": 3, "required": False},
            {"skill": "flink", "weight": 2, "required": False},
            {"skill": "linux", "weight": 2, "required": False},
        ],
        "affinity_tags": ["数据管道", "数仓建设", "数据分析", "ETL", "指标体系"],
        "knowledge_points": ["SQL 进阶（窗口函数）", "数仓分层与建模", "ETL 调度",
                             "数据质量治理", "Spark/Flink 基础"],
        "coding_topics": ["复杂 SQL 题", "指标口径设计", "数据倾斜排查"],
        "interview_focus": ["SQL 能力", "数仓设计", "数据质量意识", "项目深挖"],
    },
    # ================= 测试 =================
    {
        "category": "测试", "title": "测试开发工程师", "level": "校招",
        "description": "负责质量保障体系建设，开发测试工具与自动化能力。",
        "skill_requirements": [
            {"skill": "测试", "weight": 5, "required": True},
            {"skill": "自动化测试", "weight": 4, "required": True},
            {"skill": "python", "weight": 4, "required": False},
            {"skill": "java", "weight": 3, "required": False},
            {"skill": "计算机网络", "weight": 3, "required": False},
            {"skill": "ci/cd", "weight": 3, "required": False},
        ],
        "affinity_tags": ["自动化测试", "测试工具", "质量体系", "CI/CD"],
        "knowledge_points": ["测试用例设计", "自动化框架", "接口测试", "CI/CD 流水线", "缺陷管理"],
        "coding_topics": ["测试用例设计题", "自动化脚本编写", "接口测试方案"],
        "interview_focus": ["用例设计思维", "自动化实践", "质量意识", "工具开发"],
    },
    # ================= 运维 =================
    {
        "category": "运维", "title": "基础设施/运维开发工程师", "level": "校招",
        "description": "负责基础设施与稳定性建设，保障服务高可用。",
        "skill_requirements": [
            {"skill": "linux", "weight": 5, "required": True},
            {"skill": "docker", "weight": 4, "required": True},
            {"skill": "kubernetes", "weight": 3, "required": False},
            {"skill": "计算机网络", "weight": 4, "required": True},
            {"skill": "ci/cd", "weight": 3, "required": False},
            {"skill": "python", "weight": 3, "required": False},
        ],
        "affinity_tags": ["稳定性建设", "监控告警", "自动化运维", "CI/CD"],
        "knowledge_points": ["Linux 命令与排障", "容器与编排", "网络与 DNS/负载均衡",
                             "监控告警体系", "CI/CD 与发布"],
        "coding_topics": ["Shell/Python 脚本题", "故障排查思路", "发布回滚方案"],
        "interview_focus": ["排障能力", "自动化实践", "稳定性意识", "项目深挖"],
    },

    # ================= 算法（2026 市场热门方向） =================
    {
        "category": "算法", "title": "VLA/具身智能算法工程师", "level": "校招",
        "description": "负责 VLA 模型研发与机器人操作策略落地。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "vla", "weight": 5, "required": True},
            {"skill": "强化学习", "weight": 4, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "深度学习", "weight": 4, "required": True},
            {"skill": "cv", "weight": 3, "required": False},
            {"skill": "transformer", "weight": 3, "required": False},
        ],
        "affinity_tags": ["机器人", "大模型", "视觉感知", "落地应用", "论文/竞赛"],
        "knowledge_points": ["VLA 架构与训练范式", "模仿学习与强化学习", "Sim-to-Real 迁移",
                             "机器人操作/抓取策略", "3D 视觉基础", "数据采集与仿真"],
        "coding_topics": ["策略网络实现", "数据管道与训练脚本", "仿真环境交互", "指标与评测设计"],
        "interview_focus": ["VLA/具身项目深挖", "Sim-to-Real 实战", "论文或竞赛", "动手能力"],
    },
    {
        "category": "算法", "title": "VLA/具身智能算法工程师", "level": "社招",
        "description": "主导具身智能模型与操作策略的研发和量产落地。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "vla", "weight": 5, "required": True},
            {"skill": "强化学习", "weight": 5, "required": True},
            {"skill": "llm", "weight": 4, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "推理优化", "weight": 3, "required": False},
        ],
        "affinity_tags": ["机器人", "大模型", "多模态", "落地应用"],
        "knowledge_points": ["VLA 全链路", "真机部署与稳定性", "数据飞轮", "评测体系", "团队协作"],
        "coding_topics": ["实时推理优化", "策略回退与安全机制", "大规模训练排障"],
        "interview_focus": ["量产落地经历", "技术判断力", "失败复盘", "带团队"],
    },
    {
        "category": "算法", "title": "多模态大模型算法工程师", "level": "校招",
        "description": "负责多模态大模型训练、微调与评测。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "transformer", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "nlp", "weight": 3, "required": False},
            {"skill": "cv", "weight": 3, "required": False},
        ],
        "affinity_tags": ["大模型", "多模态", "论文/竞赛"],
        "knowledge_points": ["Transformer 全家桶", "预训练/SFT/RLHF", "多模态融合",
                             "数据构建与清洗", "评测与对齐"],
        "coding_topics": ["手写注意力/损失函数", "训练脚本与调参", "数据处理管道"],
        "interview_focus": ["论文/项目深挖", "训练细节追问", "实验设计", "复现能力"],
    },
    {
        "category": "算法", "title": "多模态大模型算法工程师", "level": "社招",
        "description": "主导多模态模型方向的技术方案与效果优化。",
        "skill_requirements": [
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "transformer", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "分布式", "weight": 3, "required": False},
            {"skill": "推理优化", "weight": 3, "required": False},
        ],
        "affinity_tags": ["大模型", "多模态", "落地应用", "论文/竞赛"],
        "knowledge_points": ["大规模训练", "对齐与安全", "推理加速", "效果归因", "技术规划"],
        "coding_topics": ["训练效率优化", "显存与性能排障", "评测系统设计"],
        "interview_focus": ["方向级技术判断", "业务效果", "论文/专利", "影响力"],
    },
    {
        "category": "算法", "title": "大模型应用工程师（Agent/RAG）", "level": "校招",
        "description": "负责 RAG/Agent 应用开发与效果调优。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "rag", "weight": 5, "required": True},
            {"skill": "智能体", "weight": 5, "required": True},
            {"skill": "llm", "weight": 4, "required": True},
            {"skill": "mysql", "weight": 2, "required": False},
        ],
        "affinity_tags": ["大模型", "落地应用", "API 设计"],
        "knowledge_points": ["RAG 架构与调优", "Prompt 工程", "Agent 设计模式",
                             "向量检索", "效果评测"],
        "coding_topics": ["RAG 链路设计", "工具调用/Function Calling 实现", "检索质量优化"],
        "interview_focus": ["应用项目深挖", "效果指标", "工程落地", "问题排查"],
    },
    {
        "category": "算法", "title": "大模型应用工程师（Agent/RAG）", "level": "社招",
        "description": "主导大模型应用架构与智能体产品化落地。",
        "skill_requirements": [
            {"skill": "智能体", "weight": 5, "required": True},
            {"skill": "rag", "weight": 5, "required": True},
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "分布式", "weight": 2, "required": False},
        ],
        "affinity_tags": ["大模型", "落地应用", "架构设计"],
        "knowledge_points": ["智能体架构", "长上下文与记忆", "成本与延迟优化", "安全与护栏"],
        "coding_topics": ["Agent 编排设计", "评测体系建设", "线上问题归因"],
        "interview_focus": ["产品化成果", "架构决策", "成本优化", "技术规划"],
    },
    {
        "category": "算法", "title": "计算机视觉/3D 视觉算法工程师", "level": "校招",
        "description": "负责 3D 视觉、深度估计、重建等方向算法研发。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "cv", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "c++", "weight": 2, "required": False},
        ],
        "affinity_tags": ["视觉感知", "论文/竞赛", "落地应用"],
        "knowledge_points": ["几何视觉基础", "深度估计/重建", "NeRF/3DGS", "检测分割", "模型部署"],
        "coding_topics": ["视觉模型实现", "数据增强", "指标复现"],
        "interview_focus": ["视觉项目深挖", "论文复现", "几何基础", "工程能力"],
    },
    {
        "category": "算法", "title": "推荐算法工程师", "level": "校招",
        "description": "负责推荐系统召回/排序策略研发。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "推荐算法", "weight": 5, "required": True},
            {"skill": "机器学习", "weight": 5, "required": True},
            {"skill": "sql", "weight": 3, "required": True},
            {"skill": "数据分析", "weight": 3, "required": False},
        ],
        "affinity_tags": ["推荐系统", "数据分析", "增长"],
        "knowledge_points": ["召回/排序/重排", "特征工程", "AB 实验", "指标体系", "模型服务"],
        "coding_topics": ["CTR 模型实现", "实验分析 SQL", "特征管道"],
        "interview_focus": ["推荐项目深挖", "实验设计", "数据敏感度", "业务理解"],
    },
    {
        "category": "算法", "title": "大模型推理工程师（MLSys/推理优化）", "level": "社招",
        "description": "负责大模型推理加速、量化与服务化能力建设。",
        "skill_requirements": [
            {"skill": "推理优化", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "c++", "weight": 4, "required": True},
            {"skill": "深度学习", "weight": 4, "required": True},
            {"skill": "分布式", "weight": 3, "required": False},
            {"skill": "linux", "weight": 3, "required": False},
        ],
        "affinity_tags": ["落地应用", "性能优化", "架构设计"],
        "knowledge_points": ["vLLM/TensorRT 生态", "量化与蒸馏", "KV Cache/显存优化",
                             "算子与并行", "服务化与调度"],
        "coding_topics": ["推理服务设计", "性能瓶颈定位", "算子实现/优化"],
        "interview_focus": ["性能成果（延迟/吞吐）", "底层功底", "落地规模", "技术深度"],
    },
    {
        "category": "算法", "title": "自动驾驶/机器人感知算法工程师", "level": "校招",
        "description": "负责感知算法（点云/视觉）研发与部署。",
        "skill_requirements": [
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "cv", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "自动驾驶", "weight": 4, "required": True},
            {"skill": "c++", "weight": 3, "required": False},
        ],
        "affinity_tags": ["视觉感知", "机器人", "落地应用"],
        "knowledge_points": ["点云处理", "多传感器融合", "检测/跟踪", "实时性要求", "部署验证"],
        "coding_topics": ["感知模型实现", "点云处理", "部署排障"],
        "interview_focus": ["感知项目深挖", "实时系统经验", "安全意识", "工程能力"],
    },
    # ================= 后端/工程（市场热门） =================
    {
        "category": "后端", "title": "大模型平台/基础架构工程师", "level": "社招",
        "description": "负责训练/推理平台与 AI 基础设施稳定性建设。",
        "skill_requirements": [
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "分布式", "weight": 5, "required": True},
            {"skill": "kubernetes", "weight": 4, "required": True},
            {"skill": "linux", "weight": 4, "required": True},
            {"skill": "推理优化", "weight": 3, "required": False},
            {"skill": "ci/cd", "weight": 3, "required": False},
        ],
        "affinity_tags": ["稳定性建设", "架构设计", "监控告警", "落地应用"],
        "knowledge_points": ["GPU 调度", "训练任务容错", "存储与数据管道", "可观测性", "容量规划"],
        "coding_topics": ["调度器/平台设计", "故障排查", "自动化脚本"],
        "interview_focus": ["平台建设成果", "故障处理", "稳定性指标", "架构能力"],
    },
    {
        "category": "后端", "title": "AI 全栈工程师", "level": "校招",
        "description": "负责 AI 应用的前后端全链路开发。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "javascript", "weight": 4, "required": True},
            {"skill": "react", "weight": 3, "required": False},
            {"skill": "vue", "weight": 3, "required": False},
            {"skill": "llm", "weight": 3, "required": True},
            {"skill": "mysql", "weight": 3, "required": False},
        ],
        "affinity_tags": ["落地应用", "API 设计", "交互体验"],
        "knowledge_points": ["Web 全链路", "LLM API 应用", "数据库基础", "部署与联调"],
        "coding_topics": ["全栈小应用设计", "流式接口实现", "数据建模"],
        "interview_focus": ["作品/项目演示", "全栈动手能力", "AI 应用理解", "学习速度"],
    },
    # ================= 产品/数据/测试（市场热门） =================
    {
        "category": "产品", "title": "AI 产品经理", "level": "校招",
        "description": "负责 AI 产品的需求洞察、设计与落地。",
        "skill_requirements": [
            {"skill": "需求分析", "weight": 5, "required": True},
            {"skill": "产品设计", "weight": 5, "required": True},
            {"skill": "llm", "weight": 3, "required": True},
            {"skill": "数据分析", "weight": 4, "required": True},
            {"skill": "用户研究", "weight": 3, "required": False},
        ],
        "affinity_tags": ["需求文档", "产品设计", "数据分析", "大模型"],
        "knowledge_points": ["AI 产品设计方法", "大模型能力边界", "评测与迭代", "数据指标", "成本体验权衡"],
        "coding_topics": ["AI 场景需求拆解", "效果评测方案设计", "体验-成本权衡题"],
        "interview_focus": ["AI 产品 sense", "案例深挖", "模型理解程度", "推动落地"],
    },
    {
        "category": "数据", "title": "数据科学家", "level": "校招",
        "description": "通过建模与实验驱动业务增长。",
        "skill_requirements": [
            {"skill": "sql", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "机器学习", "weight": 4, "required": True},
            {"skill": "数据分析", "weight": 5, "required": True},
        ],
        "affinity_tags": ["数据分析", "指标体系", "增长"],
        "knowledge_points": ["统计与实验", "因果推断基础", "建模流程", "指标体系", "可视化表达"],
        "coding_topics": ["案例分析题", "实验设计题", "建模流程题"],
        "interview_focus": ["分析案例", "实验方法", "业务理解", "表达能力"],
    },
    {
        "category": "测试", "title": "大模型评测工程师", "level": "校招",
        "description": "负责大模型/Agent 应用的质量与评测体系建设。",
        "skill_requirements": [
            {"skill": "测试", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "llm", "weight": 3, "required": True},
            {"skill": "数据分析", "weight": 3, "required": False},
            {"skill": "自动化测试", "weight": 3, "required": False},
        ],
        "affinity_tags": ["质量体系", "大模型", "测试工具"],
        "knowledge_points": ["评测集设计", "自动评测方法", "Badcase 分析", "回归体系", "安全与合规"],
        "coding_topics": ["评测脚本设计", "评测指标实现", "Badcase 归类"],
        "interview_focus": ["评测思维", "AI 应用理解", "工具能力", "细致度"],
    },
    {
        "category": "运维", "title": "MLOps/训练平台工程师", "level": "社招",
        "description": "负责模型训练、部署与运维自动化。",
        "skill_requirements": [
            {"skill": "linux", "weight": 5, "required": True},
            {"skill": "docker", "weight": 4, "required": True},
            {"skill": "kubernetes", "weight": 4, "required": True},
            {"skill": "python", "weight": 3, "required": True},
            {"skill": "ci/cd", "weight": 3, "required": False},
            {"skill": "监控告警", "weight": 3, "required": False},
        ],
        "affinity_tags": ["自动化运维", "稳定性建设", "CI/CD", "落地应用"],
        "knowledge_points": ["模型部署（推理服务）", "GPU 资源管理", "流水线自动化", "监控告警", "成本优化"],
        "coding_topics": ["部署流水线设计", "故障排查", "自动化脚本"],
        "interview_focus": ["平台/运维实践", "自动化程度", "故障处理", "成本意识"],
    },

    # ================= 算法细分方向（预训练/后训练/感知） =================
    {
        "category": "算法", "title": "大模型预训练工程师", "level": "校招",
        "description": "参与大模型预训练数据、训练流程与效率优化。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "分布式", "weight": 3, "required": False},
            {"skill": "pytorch", "weight": 4, "required": True},
        ],
        "affinity_tags": ["大模型", "数据管道", "论文/竞赛"],
        "knowledge_points": ["预训练数据构建与清洗", "语言模型训练流程", "并行策略基础",
                             "训练稳定性", "损失与指标分析"],
        "coding_topics": ["数据管道实现", "训练脚本与调参", "吞吐/显存排查"],
        "interview_focus": ["训练细节追问", "数据处理经验", "规模感", "论文/项目"],
    },
    {
        "category": "算法", "title": "大模型预训练工程师", "level": "社招",
        "description": "主导预训练数据体系与训练效率/稳定性建设。",
        "skill_requirements": [
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "分布式", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "推理优化", "weight": 2, "required": False},
        ],
        "affinity_tags": ["大模型", "架构设计", "数据管道"],
        "knowledge_points": ["数据配比与质量", "3D 并行/显存优化", "训练容错", "Scaling Law", "成本效率"],
        "coding_topics": ["大规模训练排障", "数据管道设计", "训练效率优化"],
        "interview_focus": ["预训练全流程", "规模与成本", "故障处理", "技术判断力"],
    },
    {
        "category": "算法", "title": "大模型后训练工程师（Post-training/对齐）", "level": "校招",
        "description": "参与 SFT/RLHF/DPO 等后训练对齐工作。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "强化学习", "weight": 4, "required": True},
            {"skill": "深度学习", "weight": 4, "required": True},
            {"skill": "nlp", "weight": 3, "required": False},
        ],
        "affinity_tags": ["大模型", "论文/竞赛"],
        "knowledge_points": ["SFT 数据构建", "RLHF/DPO 原理", "奖励模型", "评测与对齐", "安全与拒答"],
        "coding_topics": ["偏好数据处理", "训练脚本实现", "评测集设计"],
        "interview_focus": ["对齐方法理解", "数据 sense", "实验设计", "项目深挖"],
    },
    {
        "category": "算法", "title": "大模型后训练工程师（Post-training/对齐）", "level": "社招",
        "description": "主导后训练对齐体系与模型效果调优。",
        "skill_requirements": [
            {"skill": "llm", "weight": 5, "required": True},
            {"skill": "强化学习", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "python", "weight": 4, "required": True},
        ],
        "affinity_tags": ["大模型", "落地应用", "论文/竞赛"],
        "knowledge_points": ["对齐全链路", "Reward Hacking 规避", "效果归因", "数据飞轮", "安全合规"],
        "coding_topics": ["对齐实验设计", "评测体系", "训练排障"],
        "interview_focus": ["对齐实战", "效果与安全平衡", "方法论沉淀", "技术影响力"],
    },
    {
        "category": "算法", "title": "感知算法工程师（视觉/世界模型）", "level": "校招",
        "description": "负责感知/世界模型方向算法研发。",
        "skill_requirements": [
            {"skill": "python", "weight": 5, "required": True},
            {"skill": "cv", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "pytorch", "weight": 4, "required": True},
            {"skill": "transformer", "weight": 3, "required": False},
        ],
        "affinity_tags": ["视觉感知", "机器人", "大模型", "论文/竞赛"],
        "knowledge_points": ["检测/分割/跟踪", "多视角几何", "世界模型基础", "时序建模", "数据增强"],
        "coding_topics": ["感知模型实现", "视频数据处理", "指标复现"],
        "interview_focus": ["感知项目深挖", "几何/时序基础", "论文复现", "工程能力"],
    },
    {
        "category": "算法", "title": "感知算法工程师（视觉/世界模型）", "level": "社招",
        "description": "主导感知/世界模型算法方案与落地效果。",
        "skill_requirements": [
            {"skill": "cv", "weight": 5, "required": True},
            {"skill": "深度学习", "weight": 5, "required": True},
            {"skill": "llm", "weight": 3, "required": False},
            {"skill": "python", "weight": 4, "required": True},
            {"skill": "推理优化", "weight": 3, "required": False},
        ],
        "affinity_tags": ["视觉感知", "机器人", "多模态", "落地应用"],
        "knowledge_points": ["感知全链路", "世界模型/视频生成", "实时性与部署", "效果归因", "数据闭环"],
        "coding_topics": ["端到端方案设计", "性能优化", "线上问题归因"],
        "interview_focus": ["落地效果", "方案判断力", "论文/专利", "技术规划"],
    },
]


class Command(BaseCommand):
    help = "Seed the shared job catalog (idempotent)"

    def handle(self, *args, **options):
        created = updated = 0
        for spec in JOBS:
            obj, was_created = JobPosition.objects.update_or_create(
                category=spec["category"], title=spec["title"], level=spec["level"],
                defaults={
                    "description": spec["description"],
                    "skill_requirements": spec["skill_requirements"],
                    "affinity_tags": spec["affinity_tags"],
                    "knowledge_points": spec["knowledge_points"],
                    "coding_topics": spec["coding_topics"],
                    "interview_focus": spec["interview_focus"],
                    "is_active": True,
                },
            )
            created += was_created
            updated += not was_created
        self.stdout.write(self.style.SUCCESS(
            f"job catalog ready: {created} created, {updated} updated, "
            f"{JobPosition.objects.count()} total"))
