# Generated by Django 6.1.1 on 2026-10-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0002_resume_mineru_source_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_json', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portraits', to='resumes.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('user', 'resume_version')},
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('matched_skills', models.JSONField(default=list)),
                ('gap_skills', models.JSONField(default=list)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposition')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiling.userportrait')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
