# Generated by Django 6.1.1 on 2026-10-02 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('mimo', 'Xiaomi MiMo'), ('mineru', 'MinerU')], max_length=20)),
                ('api_key_encrypted', models.TextField()),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('base_url', models.URLField(blank=True, default='', help_text='Optional base_url override for self-hosted gateways')),
                ('is_valid', models.BooleanField(blank=True, help_text='Last validation result; null = never validated', null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
