# Generated by Django 6.1.1 on 2026-10-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(blank=True, default='', help_text='deepseek | mimo — empty = auto (deepseek first)', max_length=20)),
                ('llm_model', models.CharField(blank=True, default='', help_text='e.g. mimo-v2.6-pro / deepseek-chat — empty = provider default', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
