# Generated by Django 6.1.1 on 2026-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('前端', '前端'), ('后端', '后端'), ('算法', '算法'), ('产品', '产品'), ('数据', '数据'), ('测试', '测试'), ('运维', '运维')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('实习', '实习'), ('校招', '校招'), ('社招', '社招')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('skill_requirements', models.JSONField(default=list, help_text='[{"skill": "python", "weight": 5, "required": true}]')),
                ('affinity_tags', models.JSONField(default=list, help_text='project-tag affinities, e.g. [高并发, 分布式]')),
                ('knowledge_points', models.JSONField(default=list)),
                ('coding_topics', models.JSONField(default=list)),
                ('interview_focus', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'level'],
                'unique_together': {('category', 'title', 'level')},
            },
        ),
    ]
