# Generated by Django 6.1.1 on 2026-10-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sparr_sessions', '0004_codingquestion_codinganswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('hire_recommendation', models.CharField(choices=[('强推', '强推'), ('推荐', '推荐'), ('待定', '待定'), ('不推荐', '不推荐')], default='待定', max_length=10)),
                ('dimension_radar', models.JSONField(default=dict, help_text='{"基础知识": 0-100, "编码能力", "项目深度", "沟通表达", "岗位匹配"}')),
                ('stage_scores', models.JSONField(default=dict)),
                ('per_stage_summary', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_plan', models.JSONField(default=list)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='sparr_sessions.applicationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(blank=True, default='', help_text='如 projects[0].metrics（展示定位用）', max_length=200)),
                ('original_text', models.TextField()),
                ('suggested_text', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('apply_note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='reports.finalreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
